### ISSUE TITLE
workout appears to be empty

### ISSUE THREAD

**Issue by adrenalinenz** [jsmattsonjr/trzwo#1]
Exporting the workout appears to be empty except for the description author etc info, anything between the workout tags has no data.

![image](https://github.com/jsmattsonjr/trzwo/assets/10415305/55ccec29-eb51-4ee8-965e-dcd2a9844bae)

Error in Chrome console is "workoutData is not an array".

I tried another ZWO export tool and that didn't have an issue, not sure if it's just my setup or something not right with the code for this project though.

**Comment by jsmattsonjr** [comment]
Which workout are you trying to convert?

**Comment by jsmattsonjr** [comment]
Never mind. Something has broken in the past week or two. I'll look into it. Thanks!

**Comment by jsmattsonjr** [comment]
TrainerRoad has changed the data format very slightly. The package has been updated on github. I'll submit the changes to the Chrome Web Store, but it may take a few days. Thanks for the bug report!

**Comment by jsmattsonjr** [comment]
TrainerRoad changed the capitalization of three data fields, which "the other tool" doesn't use.

Fixed with commit 5d7699f ("May Day Package").

Tested with workouts "Striped +4" and "Pioneer -3".

Submitted to Chrome Web Store.
